export default {
  "12ccf6ed": [() => import(/* webpackChunkName: "12ccf6ed" */ "@site/docs/refinamento-de-ideia.md"), "@site/docs/refinamento-de-ideia.md", require.resolveWeak("@site/docs/refinamento-de-ideia.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "3c88cda7": [() => import(/* webpackChunkName: "3c88cda7" */ "@site/docs/guia-claude-code.md"), "@site/docs/guia-claude-code.md", require.resolveWeak("@site/docs/guia-claude-code.md")],
  "40d6bc28": [() => import(/* webpackChunkName: "40d6bc28" */ "@generated/docusaurus-plugin-content-docs/default/p/wiki-c1a.json"), "@generated/docusaurus-plugin-content-docs/default/p/wiki-c1a.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/wiki-c1a.json")],
  "58cb6919": [() => import(/* webpackChunkName: "58cb6919" */ "@site/docs/Relatório de Leads: G4 Sprint de IA.md"), "@site/docs/Relatório de Leads: G4 Sprint de IA.md", require.resolveWeak("@site/docs/Relatório de Leads: G4 Sprint de IA.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "73e848e6": [() => import(/* webpackChunkName: "73e848e6" */ "@site/docs/agentes-especializados.md"), "@site/docs/agentes-especializados.md", require.resolveWeak("@site/docs/agentes-especializados.md")],
  "a05048a0": [() => import(/* webpackChunkName: "a05048a0" */ "@site/docs/guia-desenvolvimento-ia.md"), "@site/docs/guia-desenvolvimento-ia.md", require.resolveWeak("@site/docs/guia-desenvolvimento-ia.md")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "b5acfeef": [() => import(/* webpackChunkName: "b5acfeef" */ "@site/docs/framework-openclaw-multi-agente.md"), "@site/docs/framework-openclaw-multi-agente.md", require.resolveWeak("@site/docs/framework-openclaw-multi-agente.md")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],};
